'use client'

import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
import { useRouter } from 'next/navigation'

const sections = [
  { key: 'executive_summary', label: 'Executive Summary', icon: '⭐' },
  { key: 'problem_statement', label: 'Problem Statement', icon: '🎯' },
  { key: 'solution', label: 'Our Solution', icon: '💡' },
  { key: 'market_opportunity', label: 'Market Opportunity', icon: '📈' },
  { key: 'traction', label: 'Traction', icon: '🚀' },
  { key: 'team', label: 'Team', icon: '👥' },
  { key: 'funding_use', label: 'Use of Funds', icon: '💰' },
  { key: 'impact', label: 'Impact', icon: '🌍' },
]

export default function ApplicationPage({ params }: { params: { id: string } }) {
  const router = useRouter()
  const [application, setApplication] = useState<any>(null)
  const [profile, setProfile] = useState<any>(null)
  const [grant, setGrant] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const [downloading, setDownloading] = useState(false)

  useEffect(() => {
    const fetchData = async () => {
      const { data: app } = await supabase
        .from('applications')
        .select('*')
        .eq('id', params.id)
        .single()

      if (!app) { router.push('/dashboard'); return }
      setApplication(app)

      const { data: prof } = await supabase
        .from('business_profiles')
        .select('*')
        .eq('id', app.profile_id)
        .single()
      setProfile(prof)

      const { data: gr } = await supabase
        .from('grants')
        .select('*')
        .eq('id', app.grant_id)
        .single()
      setGrant(gr)

      setLoading(false)
    }
    fetchData()
  }, [params.id, router])

  const handleDownloadText = () => {
    if (!application || !profile || !grant) return

    let content = `GRANT APPLICATION\n`
    content += `${grant.name}\n`
    content += `${'='.repeat(50)}\n\n`
    content += `Business: ${profile.business_name}\n`
    content += `Country: ${profile.country}\n`
    content += `Sector: ${profile.sector}\n\n`
    content += `${'='.repeat(50)}\n\n`

    sections.forEach(section => {
      const text = application.sections?.[section.key]
      if (text) {
        content += `${section.label.toUpperCase()}\n`
        content += `${'-'.repeat(30)}\n`
        content += `${text}\n\n`
      }
    })

    const fileName = `${profile.business_name}-${grant.name}-application.txt`
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = fileName
    a.click()
    URL.revokeObjectURL(url)

    if (typeof pendo !== 'undefined') {
      pendo.track('application_downloaded', {
        file_format: 'txt',
        business_name: profile.business_name,
        grant_name: grant.name,
        section_count: sections.filter(s => application.sections?.[s.key]).length,
        average_score: averageScore,
        file_name: fileName
      })
    }
  }

  const handleDownloadHTML = () => {
    if (!application || !profile || !grant) return
    setDownloading(true)

    let html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${profile.business_name} — ${grant.name} Application</title>
  <style>
    body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; line-height: 1.6; }
    h1 { font-size: 28px; color: #166534; border-bottom: 3px solid #166534; padding-bottom: 12px; }
    h2 { font-size: 18px; color: #166534; margin-top: 36px; margin-bottom: 8px; }
    .meta { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 16px; margin: 20px 0; }
    .meta p { margin: 4px 0; font-size: 14px; }
    .section { margin-bottom: 32px; }
    p { font-size: 15px; line-height: 1.8; }
    .divider { border: none; border-top: 1px solid #e5e7eb; margin: 32px 0; }
    .footer { text-align: center; font-size: 12px; color: #9ca3af; margin-top: 48px; }
  </style>
</head>
<body>
  <h1>${profile.business_name}</h1>
  <p style="font-size:18px; color:#4b5563;">${grant.name} Application</p>
  
  <div class="meta">
    <p><strong>Business:</strong> ${profile.business_name}</p>
    <p><strong>Country:</strong> ${profile.country}</p>
    <p><strong>Sector:</strong> ${profile.sector}</p>
    <p><strong>Stage:</strong> ${profile.stage}</p>
  </div>
  <hr class="divider">`

    sections.forEach(section => {
      const text = application.sections?.[section.key]
      if (text) {
        html += `
  <div class="section">
    <h2>${section.icon} ${section.label}</h2>
    <p>${text.replace(/\n/g, '<br/>')}</p>
  </div>`
      }
    })

    html += `
  <hr class="divider">
  <div class="footer">Generated by GrantPilot — grantpilot.vercel.app</div>
</body>
</html>`

    const fileName = `${profile.business_name}-${grant.name}-application.html`
    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = fileName
    a.click()
    URL.revokeObjectURL(url)

    if (typeof pendo !== 'undefined') {
      pendo.track('application_downloaded', {
        file_format: 'html',
        business_name: profile.business_name,
        grant_name: grant.name,
        section_count: sections.filter(s => application.sections?.[s.key]).length,
        average_score: averageScore,
        file_name: fileName
      })
    }

    setDownloading(false)
  }

  const averageScore = application?.scores
    ? Math.round(
        Object.values(application.scores as Record<string, number>)
          .reduce((a, b) => a + b, 0) /
        Object.values(application.scores as Record<string, number>).length
      )
    : 0

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-gray-500">Loading your application...</div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-[#FDF6EC]">
      {/* Header */}
      <header className="bg-white border-b border-[#D6C4AF]">
        <div className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-[#1B4332] rounded-lg flex items-center justify-center">
              <span className="text-white text-sm font-bold">G</span>
            </div>
            <span className="font-bold text-gray-900">GrantPilot</span>
          </div>
          <button
            onClick={() => router.push('/dashboard')}
            className="text-sm text-gray-500 hover:text-gray-700"
          >
            ← Dashboard
          </button>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-10">

        {/* Summary card */}
        <div className="bg-white rounded-2xl border border-[#D6C4AF] p-6 mb-6">
          <div className="flex items-start justify-between">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">
                {profile?.business_name}
              </h1>
              <p className="text-gray-500 mt-1">{grant?.name} Application</p>
              <div className="flex items-center gap-4 mt-3">
                <span className="text-sm text-gray-500">
                  📍 {profile?.country}
                </span>
                <span className="text-sm text-gray-500">
                  🏭 {profile?.sector}
                </span>
                <span className="text-sm text-gray-500">
                  📊 {profile?.stage}
                </span>
              </div>
            </div>

            {/* Overall score */}
            <div className="text-center">
              <div className={`w-16 h-16 rounded-full flex items-center justify-center text-xl font-bold ${
                averageScore >= 80 ? 'bg-[#DCF0E4] text-[#1B4332]' :
                averageScore >= 60 ? 'bg-yellow-100 text-yellow-700' :
                'bg-red-100 text-red-700'
              }`}>
                {averageScore}
              </div>
              <p className="text-xs text-gray-400 mt-1">Overall Score</p>
            </div>
          </div>

          {/* Download buttons */}
          <div className="flex gap-3 mt-6 pt-6 border-t border-[#E8D9C8]">
            <button
              onClick={handleDownloadHTML}
              disabled={downloading}
              className="flex-1 bg-[#1B4332] hover:bg-[#2D6A4F] text-white font-medium py-2.5 rounded-lg text-sm transition-colors disabled:opacity-50"
            >
              📄 Download as HTML
            </button>
            <button
              onClick={handleDownloadText}
              className="flex-1 bg-white hover:bg-[#FDF6EC] text-gray-700 font-medium py-2.5 rounded-lg text-sm border border-[#D6C4AF] transition-colors"
            >
              📝 Download as Text
            </button>
            <button
              onClick={() => router.push(`/generate/${application?.id}`)}
              className="px-4 bg-white hover:bg-[#FDF6EC] text-gray-700 font-medium py-2.5 rounded-lg text-sm border border-[#D6C4AF] transition-colors"
            >
              ✏️ Edit
            </button>
          </div>
        </div>

        {/* Sections */}
        <div className="space-y-4">
          {sections.map(section => {
            const content = application?.sections?.[section.key]
            const score = application?.scores?.[section.key]
            if (!content) return null

            return (
              <div key={section.key} className="bg-white rounded-2xl border border-[#D6C4AF] p-6">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <span>{section.icon}</span>
                    <h2 className="font-bold text-gray-900">{section.label}</h2>
                  </div>
                  {score && (
                    <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${
                      score >= 80 ? 'bg-[#DCF0E4] text-[#1B4332]' :
                      score >= 60 ? 'bg-yellow-100 text-yellow-700' :
                      'bg-red-100 text-red-700'
                    }`}>
                      {score}/100
                    </span>
                  )}
                </div>
                <p className="text-gray-700 leading-relaxed text-sm whitespace-pre-wrap">
                  {content}
                </p>
              </div>
            )
          })}
        </div>

        {/* Apply to another grant */}
        <div className="mt-8 bg-[#F5E6D3] border border-[#D6C4AF] rounded-2xl p-6 text-center">
          <h3 className="font-bold text-[#1B4332] mb-1">Apply to another grant</h3>
          <p className="text-[#1B4332] text-sm mb-4">
            Your business profile is saved. Generate a new application in minutes.
          </p>
          <button
            onClick={() => router.push(`/apply/${application?.profile_id}`)}
            className="bg-[#1B4332] hover:bg-[#2D6A4F] text-white font-medium px-6 py-2.5 rounded-lg text-sm transition-colors"
          >
            Choose Another Grant →
          </button>
        </div>

      </main>
    </div>
  )
}